version: "3.9"
services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - ${PWD}/CONFIG.yml:/CONFIG.yml
    expose: ["8000"]
    labels:  # see https://doc.traefik.io/traefik/routing/providers/docker/ for all labels
     - "traefik.enable=true"
     - "traefik.http.routers.error-demo.rule=Host(`errors.danya02.ru`)"
     - "traefik.http.routers.error-demo.entrypoints=web"
     - "traefik.http.services.error-demo.loadbalancer.server.port=8000"

    networks:
     - proxy

networks:
  proxy:
    external: true
